# Name of this app
service: fizzy
image: thinkoodle/fizzy

#-- About your deployment --#

volumes:
  - "/data/fizzy/storage:/rails/storage"

servers:
  web:
    - 5.161.50.69

ssh:
  user: root

proxy:
  ssl: true
  host: fizzy.heyoodle.com
  healthcheck:
    path: /up
    interval: 3
    timeout: 60

env:
  secret:
    - SECRET_KEY_BASE
    - VAPID_PUBLIC_KEY
    - VAPID_PRIVATE_KEY
    - SMTP_USERNAME
    - SMTP_PASSWORD
    - OPENCLAW_HOOK_TOKEN
  clear:
    BASE_URL: https://fizzy.heyoodle.com
    MAILER_FROM_ADDRESS: fizzy@heyoodle.com
    SMTP_ADDRESS: smtp.resend.com
    SMTP_PORT: "587"
    MULTI_TENANT: false
    SOLID_QUEUE_IN_PUMA: true
    OPENCLAW_RELAY_URL: http://10.0.0.3:18795
    OPENCLAW_HOOK_URL: http://10.0.0.3:18789/hooks/fizzy

#-- General configuration --#

registry:
  server: ghcr.io
  username: ryanrhughes
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  remote: ssh://root@5.161.50.69
  cache:
    type: registry
    options: mode=max
    image: thinkoodle/fizzy-build-cache

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"
