# Name of this app
service: fizzy
image: ghcr.io/thinkoodle/fizzy

#-- About your deployment --#

servers:
  web:
    - 5.161.50.69

ssh:
  user: root

proxy:
  ssl: true
  host: fizzy.heyoodle.com

env:
  secret:
    - SECRET_KEY_BASE
    - VAPID_PUBLIC_KEY
    - VAPID_PRIVATE_KEY
    - SMTP_USERNAME
    - SMTP_PASSWORD
    - OPENCLAW_HOOK_TOKEN
  clear:
    BASE_URL: https://fizzy.heyoodle.com
    MAILER_FROM_ADDRESS: sheldon@heyoodle.com
    SMTP_ADDRESS: smtp.postmarkapp.com
    MULTI_TENANT: false
    SOLID_QUEUE_IN_PUMA: true
    OPENCLAW_RELAY_URL: http://10.0.0.3:18795
    OPENCLAW_HOOK_URL: http://10.0.0.3:18789/hooks/fizzy

#-- General configuration --#

registry:
  server: ghcr.io
  username: ThinkOodle
  password:
    - KAMAL_REGISTRY_PASSWORD

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"
